spring:
  application:
    name: casting_sportclub_bot
  datasource:
    url: jdbc:postgresql://localhost:5435/SSCBot
    username: pguser
    password: hugo4POS123
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379

telegram:
  token: ${BOT_TOKEN}
  username: ${BOT_NAME}
  url: ${BOT_URL}

server:
  port: 8080